# Generated by Django 5.2.4 on 2025-08-18 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=24, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=128, verbose_name='título')),
                ('short', models.CharField(max_length=256, verbose_name='resumen')),
                ('cover', models.ImageField(upload_to='forum_cover_images', verbose_name='portada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creación')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'foro',
                'verbose_name_plural': 'foros',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, verbose_name='slug')),
                ('title', models.CharField(max_length=128, verbose_name='título')),
                ('preimagebody', models.TextField(blank=True, default=None, verbose_name='texto previo')),
                ('image', models.ImageField(upload_to='post_images', verbose_name='imágen')),
                ('body', models.TextField(verbose_name='texto principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creación')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.forum', verbose_name='tema')),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
                'indexes': [models.Index(fields=['forum', 'slug'], name='idx_post_forum_slug')],
                'constraints': [models.UniqueConstraint(fields=('forum', 'slug'), name='unique_post_forum_slug')],
            },
        ),
    ]
