# Generated by Django 5.2.4 on 2025-08-20 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='texto del comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creación')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.post', verbose_name='publicación')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Highlighted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.post', verbose_name='publicación destacada')),
            ],
            options={
                'verbose_name': 'destacado',
                'verbose_name_plural': 'destacados',
            },
        ),
    ]
