# Generated by Django 5.2.4 on 2025-08-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Post Image', 'verbose_name_plural': 'Post Images'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
